const BAD_REQUEST = 400;
const UNAUTHORIZED_ERROR = 401;
const NOT_FOUND = 404;
const FORBIDDEN_ERROR = 403;
const CONFLICT_ERROR = 409;
const SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  SERVER_ERROR,
  FORBIDDEN_ERROR,
  UNAUTHORIZED_ERROR,
  CONFLICT_ERROR,
};
